export const ServiceCategory = {
  PLUMBING: "PLUMBING",
  ELECTRICAL: "ELECTRICAL",
  CLEANING: "CLEANING",
  HANDYMAN: "HANDYMAN",
  LANDSCAPING: "LANDSCAPING",
  HVAC: "HVAC",
  PAINTING: "PAINTING",
  CARPENTRY: "CARPENTRY",
  ROOFING: "ROOFING",
  FLOORING: "FLOORING",
  SNOW_REMOVAL: "SNOW_REMOVAL",
  PEST_CONTROL: "PEST_CONTROL",
  APPLIANCE_INSTALLATION: "APPLIANCE_INSTALLATION",
  FURNITURE_ASSEMBLY: "FURNITURE_ASSEMBLY",
  TV_MOUNTING: "TV_MOUNTING",
  SMART_HOME_INSTALLATION: "SMART_HOME_INSTALLATION",
  MOVING_SERVICES: "MOVING_SERVICES",
  JUNK_REMOVAL: "JUNK_REMOVAL",
  IT_SUPPORT: "IT_SUPPORT",
  OTHER: "OTHER",
};

export const PricingType = {
  HOURLY: "HOURLY",
  FIXED: "FIXED",
};
